language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1.3

env:
  global:
    - APP_ENV=test
    - DB_CONNECTION=pgsql
    - DB_DATABASE=travis_ci_test
    - DB_USERNAME=postgres

services:
  - postgresql

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - mkdir -p ./bootstrap/cache
  - composer install --prefer-dist --no-interaction

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - php artisan migrate --seed

script:
  - mkdir -p tests/logs
  - composer test:coverage

after_success:
  - php vendor/bin/php-coveralls -v
